'use strict'

module.exports = (() => {
    class Identifiers {
        static RED_FLAGS() {
            return [
                "anjing",
                "bajingan",
                "bangsat",
                "brengsek",
                "goblok",
                "goblog",
                "geblek",
                "gebleg",
                "bego",
                "bodoh",
                "idiot",
                "kampret",
                "keparat",
                "kontol",
                "memek",
                "ngentot",
                "perek",
                "tai",
                "tolol",
                "jancuk",
                "pepek",
                "asw",
                "pecun",
                "tempe",
                "anjing",
                "bajingan",
                "bangsat",
                "brengsek",
                "goblok",
                "kampret",
                "keparat",
                "kontol",
                "memek",
                "ngentot",
                "perek",
                "tai",
                "tolol",
                "jancuk",
                "pepek",
                "asw",
                "pecun",
                "tempe",
                "Ajg",
                "Kntl",
                "Mmk",
                "Bgst",
                "Kmk",
                "Pki",
                "Ckmy",
                "Asu",
                "Tele",
                "Kirik",
                "Jaran",
                "Jnck",
                "Fck",
                "bitch",
                "bich",
                "asshole",
                "bangsad",
                "bangsat",
                "memek",
                "pukimak",
                "puki"
            ]
        }

        static VALID() {
            return [
                "pesanan",
                "barang",
                "order",
                "status",
                "kapan",
                "sampai",
                "pengiriman",
                "tracking",
                "nomor pesanan",
                "resi",
                "keterlambatan",
                "belum datang",
                "terlambat",
                "hilang",
                "gagal",
                "kapan tiba",
                "kapan sampai",
                "dimana barang",
                "kemana barang",
                "proses",
                "konfirmasi",
                "cek",
                "tolong",
                "bantu",
                "masalah",
                "kendala",
                "komplain",
                "keluhan",
                "pengecekan"
            ]
        }

        static QUERIES() {
            return [
                "pesenan",
                "psenan",
                "psanan",
                "order",
                "ordr",
                "pesanan",
                "barang",
                "order",
                "status",
                "kapan",
                "sampai",
                "pengiriman",
                "tracking",
                "nomor pesanan",
                "resi",
                "keterlambatan",
                "belum datang",
                "terlambat",
                "hilang",
                "gagal",
                "sampe",
                "dah dimana",
                "dah tiba",
                "kapan tiba",
                "kapan sampai",
                "dimana barang",
                "kemana barang",
                "proses",
                "konfirmasi",
                "cek",
                "pengecekan"
            ]
        }
    }

    return Identifiers
})()